name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
        toolchain: [stable, beta]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.toolchain }}
        override: true

    - name: Install alsa
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev

    - name: Install udev
      if: ${{ runner.os == 'Linux' }}
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev

    - name: Run cargo check --all-targets w/ -D warnings
      run: cargo check --all-targets
      env:
        RUSTFLAGS: "-D warnings"

    - name: Run cargo test w/ -D warnings
      if: ${{ runner.os == 'Linux' }}
      run: cargo test headless -- --test-threads=1
      env:
        RUSTFLAGS: "-D warnings"

  rustfmt:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get nightly Rust toolchain with rustfmt
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true
        components: rustfmt

    - name: Run cargo fmt --all -- --check
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Get stable Rust toolchain with clippy
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy

    - name: Install alsa
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev

    - name: Install udev
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev

    - name: Run cargo clippy --all-targets --package ggez -- -D warnings
      run: cargo clippy --all-targets --package ggez -- -D warnings